// Run with an Expo web dev server and PLAYWRIGHT_MODULE pointing to playwright.
const assert = require("node:assert/strict");
const path = require("node:path");
const fs = require("node:fs");
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const db = require("../src/common/db");
const query = (sql, args = []) => db.promise().query(sql, args).then(([rows]) => rows);

async function run() {
  const fixture = "ui_" + Date.now();
  const password = "FixturePassword123";
  let accountId, profileId, exerciseId, alternativeId, server, browser;
  const screenshots = path.resolve(__dirname, "../../FE_GymPlan/Client_GymUser/GymPlan/.expo/verification");
  fs.mkdirSync(screenshots, { recursive: true });
  try {
    accountId = (await query("INSERT INTO Accounts (username, email, password, role) VALUES (?, ?, ?, 'GYM_USER')", [fixture, fixture + "@example.test", password])).insertId;
    profileId = (await query("INSERT INTO GymUsers (accountId, fullName, sessionsPerWeek) VALUES (?, 'UI Test User', 3)", [accountId])).insertId;
    const description = "Hướng dẫn thực hiện:\n1. Nội dung kiểm thử bước một.\n2. Nội dung kiểm thử bước hai.\n3. Nội dung kiểm thử bước ba.\n4. Nội dung kiểm thử bước bốn.\nLỗi thường gặp:\n- Nội dung kiểm thử lỗi thường gặp.";
    exerciseId = (await query("INSERT INTO Exercises (name, description, difficulty) VALUES (?, ?, 'EASY')", [fixture + " Exercise", description])).insertId;
    alternativeId = (await query("INSERT INTO Exercises (name, description, difficulty) VALUES (?, ?, 'MEDIUM')", [fixture + " Alternative", description])).insertId;
    await query("INSERT INTO ExerciseAlternatives (exerciseId, alternativeExerciseId, priority, note) VALUES (?, ?, 1, 'UI alternative note')", [exerciseId, alternativeId]);
    const [muscle] = await query("SELECT groupId FROM MuscleGroups WHERE groupName = 'Chest' LIMIT 1");
    assert.ok(muscle, "UI fixture requires the existing Chest muscle group");
    await query("INSERT INTO ExerciseMuscleGroups (exerciseId, groupId, role) VALUES (?, ?, 'PRIMARY')", [exerciseId, muscle.groupId]);
    const equipment = await query("SELECT equipmentId, equipmentName FROM Equipment ORDER BY equipmentName LIMIT 2");
    assert.equal(equipment.length, 2);
    for (const item of equipment) await query("INSERT INTO ExerciseEquipment (exerciseId, equipmentId) VALUES (?, ?)", [exerciseId, item.equipmentId]);
    const planId = (await query("INSERT INTO WorkoutPlans (title, creatorId, isTemplate, durationWeeks) VALUES (?, ?, TRUE, 8)", [fixture + " Plan", accountId])).insertId;
    const dayId = (await query("INSERT INTO WorkoutDays (planId, dayName, `order`, weekDay) VALUES (?, 'Test Day', 1, WEEKDAY(CURDATE()) + 1)", [planId])).insertId;
    await query("INSERT INTO ExerciseConfigs (exerciseId, dayId, sets, reps, restTime, `order`) VALUES (?, ?, 2, 10, 60, 1)", [exerciseId, dayId]);
    server = require("../src/app").listen(0, "127.0.0.1");
    await new Promise(resolve => server.once("listening", resolve));
    const apiUrl = `http://127.0.0.1:${server.address().port}`;
    browser = await chromium.launch({ channel: "msedge", headless: true });
    const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
    page.setDefaultTimeout(25000);
    page.setDefaultNavigationTimeout(60000);
    const errors = [];
    const requests = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("request", request => requests.push(request.url()));
    // Route the frontend's configured localhost API to this isolated test server.
    await page.route(/http:\/\/(localhost|127\.0\.0\.1):3000\//, async route => {
      const url = new URL(route.request().url());
      const response = await route.fetch({ url: apiUrl + url.pathname + url.search });
      await route.fulfill({ response });
    });
    await page.goto(process.env.GYM_WEB_URL || "http://localhost:8082", { waitUntil: "domcontentloaded" });
    await page.getByPlaceholder("Nhập email", { exact: true }).fill(fixture + "@example.test");
    await page.getByPlaceholder("Nhập mật khẩu", { exact: true }).fill(password);
    await page.getByText("ĐĂNG NHẬP  →", { exact: true }).click();
    await page.waitForURL("**/home");
    await page.getByText("Lịch mẫu", { exact: true }).click();
    await page.getByText(fixture + " Plan", { exact: true }).waitFor();
    await page.getByText(fixture + " Plan", { exact: true }).locator("..").getByRole("button", { name: "Xem chi tiết →" }).click();
    await page.getByRole("button", { name: "SỬ DỤNG LỊCH NÀY" }).click();
    await page.getByText("Áp dụng lịch mẫu?", { exact: true }).waitFor();
    await page.screenshot({ path: path.join(screenshots, "apply-template.png"), fullPage: true });
    await page.getByRole("button", { name: "✓ Áp dụng lịch tập này", exact: true }).click();
    await page.waitForURL("**/plans");
    await page.getByText("START WORKOUT (Test Day)", { exact: true }).click();
    await page.waitForURL("**/workout?**");
    await page.getByLabel("Khối lượng hiệp 1 (kg)").fill("25");
    await page.getByText("Nhóm cơ: Chest", { exact: true }).waitFor();
    await page.getByText("Dụng cụ: " + equipment.map(item => item.equipmentName).join(", "), { exact: true }).waitFor();
    await page.getByText("Mục tiêu RPE: Chưa thiết lập", { exact: true }).waitFor();
    await page.getByRole("button", { name: "Xác nhận hiệp", exact: true }).first().click();
    await page.getByRole("button", { name: "✓ Đã lưu", exact: true }).waitFor();
    await page.getByRole("button", { name: "+30s", exact: true }).waitFor();
    await page.screenshot({ path: path.join(screenshots, "workout.png"), fullPage: true });
    await page.reload({ waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "✓ Đã lưu", exact: true }).waitFor();
    assert.equal(Number(await page.getByLabel("Khối lượng hiệp 1 (kg)").inputValue()), 25);
    const alternativesUrl = `**/api/user/${profileId}/exercises/${exerciseId}/alternatives`;
    await page.route(alternativesUrl, route => route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ message: "UI alternatives retry fixture" }) }));
    await page.getByRole("button", { name: "Đổi bài tập", exact: true }).click();
    await page.getByText("UI alternatives retry fixture", { exact: true }).waitFor();
    await page.unroute(alternativesUrl);
    await page.getByText("Thử lại", { exact: true }).click();
    await page.getByText("UI alternative note", { exact: true }).waitFor();
    // Wait for the native Modal fade before capturing its appearance.
    await page.waitForTimeout(350);
    await page.screenshot({ path: path.join(screenshots, "exercise-alternatives.png"), fullPage: true });
    await page.getByRole("button", { name: "Chọn " + fixture + " Alternative", exact: true }).click();
    await page.getByText(/Các hiệp đã lưu sẽ được giữ nguyên/).waitFor();
    await page.getByRole("button", { name: "Quay lại", exact: true }).click();
    assert.equal(Number(await page.getByLabel("Khối lượng hiệp 1 (kg)").inputValue()), 25);
    await page.getByRole("button", { name: "Đổi bài tập", exact: true }).click();
    await page.getByRole("button", { name: "Chọn " + fixture + " Alternative", exact: true }).click();
    await page.getByRole("button", { name: "Xác nhận", exact: true }).click();
    await page.getByText("Thay thế cho: " + fixture + " Exercise", { exact: true }).waitFor();
    await page.getByLabel("Khối lượng hiệp 1 (kg)").waitFor();
    assert.equal(await page.getByLabel("Khối lượng hiệp 1 (kg)").inputValue(), "");
    await page.getByText("2 hiệp × 10 lần • Nghỉ 60s", { exact: true }).waitFor();
    assert.ok(requests.some(url => url.includes(`/exercises/${alternativeId}/previous-performance`)));
    await page.getByLabel("Khối lượng hiệp 1 (kg)").fill("12");
    await page.getByRole("button", { name: "Xác nhận hiệp", exact: true }).first().click();
    await page.getByRole("button", { name: "✓ Đã lưu", exact: true }).waitFor();
    await page.reload({ waitUntil: "domcontentloaded" });
    await page.getByText("Thay thế cho: " + fixture + " Exercise", { exact: true }).waitFor();
    await page.getByRole("button", { name: "✓ Đã lưu", exact: true }).waitFor();
    assert.equal(Number(await page.getByLabel("Khối lượng hiệp 1 (kg)").inputValue()), 12);
    await page.screenshot({ path: path.join(screenshots, "workout-substituted.png"), fullPage: true });
    await page.getByRole("button", { name: "Đổi bài tập", exact: true }).click();
    await page.getByRole("button", { name: "Quay lại bài gốc", exact: true }).click();
    await page.getByRole("button", { name: "Xác nhận", exact: true }).click();
    await page.getByText(fixture + " Exercise", { exact: true }).waitFor();
    await page.reload({ waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "✓ Đã lưu", exact: true }).waitFor();
    assert.equal(Number(await page.getByLabel("Khối lượng hiệp 1 (kg)").inputValue()), 25);
    await query("DELETE FROM ExerciseAlternatives WHERE exerciseId = ? AND alternativeExerciseId = ?", [exerciseId, alternativeId]);
    await page.getByRole("button", { name: "Đổi bài tập", exact: true }).click();
    await page.getByText("Không có bài tập thay thế phù hợp.", { exact: true }).waitFor();
    await page.getByRole("button", { name: "Đóng", exact: true }).click();
    await page.getByRole("button", { name: "Hoàn thành bài tập", exact: true }).click();
    await page.getByRole("button", { name: "KẾT THÚC BUỔI TẬP", exact: true }).click();
    await page.getByRole("button", { name: "Xác nhận", exact: true }).click();
    await page.waitForURL(/\/history\/\d+/);
    await page.getByText("25 kg × 10 lần", { exact: true }).waitFor();
    await page.getByText("12 kg × 10 lần", { exact: true }).waitFor();
    await page.getByText("Thay thế cho: " + fixture + " Exercise", { exact: true }).waitFor();
    await page.screenshot({ path: path.join(screenshots, "history-substituted.png"), fullPage: true });
    await page.getByRole("button", { name: "Xem tiến trình", exact: true }).click();
    await page.waitForURL("**/progress");
    await page.getByText("PR MỚI", { exact: true }).first().waitFor();
    await page.screenshot({ path: path.join(screenshots, "progress.png"), fullPage: true });
    await page.getByRole("tab", { name: "Thư viện", exact: true }).click();
    await page.getByPlaceholder("Tìm kiếm bài tập (vd: Bench, Squa...").fill(fixture);
    for (const label of ["Tất cả", "Ngực", "Lưng", "Chân", "Vai", "Tay", "Bụng"]) await page.getByRole("button", { name: "Lọc nhóm cơ " + label, exact: true }).waitFor();
    await page.getByRole("button", { name: "Lọc nhóm cơ Bụng", exact: true }).click();
    await page.getByText("Không tìm thấy bài tập phù hợp", { exact: true }).waitFor();
    await page.getByRole("button", { name: "Lọc nhóm cơ Ngực", exact: true }).click();
    await page.getByText(fixture + " Exercise", { exact: true }).waitFor();
    await page.screenshot({ path: path.join(screenshots, "library.png"), fullPage: true });
    await page.getByText(fixture + " Exercise", { exact: true }).click();
    await page.waitForURL(/\/exercises\/\d+/);
    await page.getByText("Kỷ lục của bạn", { exact: true }).waitFor();
    await page.getByText("25 KG", { exact: true }).waitFor();
    for (let step = 1; step <= 4; step++) await page.getByText("BƯỚC " + step, { exact: true }).waitFor();
    await page.getByText("Lỗi thường gặp", { exact: true }).waitFor();
    await page.screenshot({ path: path.join(screenshots, "exercise-guide.png"), fullPage: true });
    await page.goto((process.env.GYM_WEB_URL || "http://localhost:8082") + "/plans", { waitUntil: "domcontentloaded" });
    await page.getByText("Tạo lịch mới", { exact: true }).click();
    await page.getByLabel("Tên chương trình", { exact: true }).fill(fixture + " Custom");
    await page.getByRole("button", { name: "+ Thêm bài tập", exact: true }).click();
    await page.getByLabel("Tìm bài tập", { exact: true }).fill(fixture);
    await page.getByRole("button", { name: fixture + " Exercise", exact: true }).click();
    await page.getByRole("button", { name: "LƯU VÀ ÁP DỤNG LỊCH", exact: true }).click();
    await page.getByRole("button", { name: "Xác nhận", exact: true }).click();
    await page.waitForURL("**/plans");
    await page.getByText(fixture + " Custom", { exact: true }).waitFor();
    await page.goto((process.env.GYM_WEB_URL || "http://localhost:8082") + "/profile", { waitUntil: "domcontentloaded" });
    await page.getByText("Đổi mật khẩu & Bảo mật", { exact: true }).click();
    await page.getByLabel("Mật khẩu hiện tại").fill(password);
    await page.getByLabel("Mật khẩu mới (6–255 ký tự)").fill("ChangedPassword123");
    await page.getByLabel("Nhập lại mật khẩu mới").fill("ChangedPassword123");
    await page.getByRole("button", { name: "Lưu mật khẩu", exact: true }).click();
    await page.getByText("✓ Đã đổi mật khẩu thành công.", { exact: true }).waitFor();
    await page.getByRole("button", { name: "Đóng", exact: true }).click();
    await page.getByText("Đăng xuất", { exact: true }).click();
    await page.getByPlaceholder("Nhập email", { exact: true }).waitFor();
    await page.reload({ waitUntil: "domcontentloaded" });
    await page.getByPlaceholder("Nhập email", { exact: true }).waitFor();
    assert.deepEqual(errors, []);
    console.log("PASS: login → template → workout → substitute/cancel/resume/restore → history → PR → exercise detail → custom plan → password → logout.");
  } catch (error) {
    if (browser) for (const context of browser.contexts()) for (const page of context.pages()) {
      await page.screenshot({ path: path.join(screenshots, "failure.png"), fullPage: true }).catch(() => {});
    }
    throw error;
  } finally {
    if (browser) await browser.close();
    if (server) await new Promise(resolve => server.close(resolve));
    if (profileId) await query("DELETE FROM WorkoutSessions WHERE profileId = ?", [profileId]);
    if (accountId) {
      await query("DELETE FROM WorkoutPlans WHERE creatorId = ?", [accountId]);
      await query("DELETE FROM Accounts WHERE accountId = ?", [accountId]);
    }
    if (exerciseId) await query("DELETE FROM Exercises WHERE exerciseId = ?", [exerciseId]);
    if (alternativeId) await query("DELETE FROM Exercises WHERE exerciseId = ?", [alternativeId]);
    await db.promise().end();
  }
}
run().catch(error => { console.error(error.message); process.exitCode = 1; });
