import { StyleSheet } from "react-native";

export const colors = {
  background: "#0D1112",
  surface: "#1B1F20",
  surfaceRaised: "#202425",
  surfaceSoft: "#2B3031",
  text: "#E9EBE8",
  muted: "#B5BDB2",
  green: "#8CFF2E",
  greenDark: "#1D411D",
  peach: "#FFB08F",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { paddingHorizontal: 23, paddingTop: 13, paddingBottom: 105 },
  personalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  activeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: colors.surfaceSoft,
  },
  activeDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.green,
  },
  activeText: { color: colors.green, fontSize: 12, fontWeight: "700" },
  heading: {
    color: colors.text,
    fontSize: 28,
    fontWeight: "900",
    marginTop: 7,
    marginBottom: 20,
  },
  routineCard: {
    backgroundColor: colors.surface,
    borderRadius: 15,
    padding: 24,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#222829",
  },
  routineTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  routineLabel: {
    color: colors.peach,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  routineName: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "800",
    marginTop: 8,
  },
  routineSubtitle: { color: colors.muted, fontSize: 16, marginTop: 5 },
  routineCopy: { flex: 1, minWidth: 0 },
  routineDetails: { gap: 8, marginTop: 20 },
  detailHeader: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 24 },
  backButton: { padding: 8 },
  backIcon: { color: colors.green, fontSize: 26 },
  detailTitle: { color: colors.text, fontSize: 25, fontWeight: "800", flex: 1 },
  levelBadge: {
    color: colors.text,
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 10,
    fontSize: 14,
    fontWeight: "700",
  },
  routineProgressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 29,
    marginBottom: 10,
  },
  weekText: { color: colors.text, fontSize: 14, fontWeight: "800" },
  completeText: { color: colors.green, fontSize: 14, fontWeight: "800" },
  progressTrack: {
    height: 10,
    borderRadius: 6,
    backgroundColor: "#303535",
    overflow: "hidden",
  },
  progressFill: {
    width: "75%",
    height: "100%",
    borderRadius: 6,
    backgroundColor: colors.green,
  },
  actionRow: { flexDirection: "row", gap: 14, marginBottom: 29 },
  actionButton: {
    flex: 1,
    height: 57,
    borderRadius: 14,
    backgroundColor: colors.surfaceSoft,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  actionPlus: { color: colors.green, fontSize: 27, lineHeight: 27 },
  actionIcon: { color: colors.muted, fontSize: 20 },
  actionText: { color: colors.text, fontSize: 16, fontWeight: "800" },
  routeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  routeTitle: { color: colors.text, fontSize: 21, fontWeight: "800" },
  routeCount: { color: colors.muted, fontSize: 14, fontWeight: "700" },
  dayCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    marginBottom: 16,
    padding: 18,
  },
  expandedDayCard: { paddingBottom: 17 },
  dayHeader: { flexDirection: "row", alignItems: "center" },
  dayIcon: {
    width: 47,
    height: 47,
    borderRadius: 10,
    backgroundColor: colors.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  dayIconActive: { backgroundColor: colors.greenDark },
  dayIconText: { color: colors.muted, fontSize: 22 },
  dayCopy: { flex: 1, minWidth: 0 },
  dayTitleRow: { flexDirection: "row", alignItems: "center", gap: 9 },
  dayTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "900",
    flexShrink: 1,
  },
  todayBadge: {
    color: "#0D170B",
    backgroundColor: colors.green,
    borderRadius: 14,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 13,
    fontWeight: "900",
  },
  dayDetails: { color: colors.muted, fontSize: 14, marginTop: 4 },
  chevron: { color: colors.muted, fontSize: 24, marginLeft: 8 },
  exerciseList: { gap: 9, marginTop: 18 },
  exerciseRow: {
    minHeight: 101,
    borderRadius: 11,
    backgroundColor: colors.surfaceRaised,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  dragHandle: {
    color: colors.muted,
    fontSize: 24,
    width: 22,
    textAlign: "center",
    marginRight: 11,
  },
  thumbnail: {
    width: 48,
    height: 58,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  thumbnailIcon: { color: "#C8D6C9", fontSize: 22 },
  previewMedia: { width: "100%", height: "100%", borderRadius: 8 },
  previewLoading: { position: "absolute" },
  exerciseCopy: { flex: 1, minWidth: 0 },
  exerciseName: { color: colors.text, fontSize: 18, fontWeight: "800" },
  exerciseStats: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  sets: { color: colors.green, fontSize: 14, fontWeight: "900" },
  weight: { color: colors.muted, fontSize: 14, marginLeft: 6 },
  rest: { color: colors.muted, fontSize: 14, marginTop: 7 },
  exerciseActions: {
    alignSelf: "stretch",
    justifyContent: "space-around",
    marginLeft: 9,
  },
  editIcon: {
    color: colors.muted,
    fontSize: 23,
    transform: [{ rotate: "-35deg" }],
  },
  startButton: {
    height: 66,
    borderRadius: 15,
    backgroundColor: colors.green,
    marginTop: 35,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 14,
    shadowColor: colors.green,
    shadowOpacity: 0.32,
    shadowRadius: 12,
    elevation: 4,
  },
  playIcon: { color: "#0D170B", fontSize: 19 },
  startText: {
    color: "#0D170B",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
});
